version: '2'
services:

  kapacitor: 
    build: ./kapacitor
    container_name: kapacitor
    ports:
      - "9092:9092"

  influxdb: 
    image: influxdb:alpine
    container_name: influxdb
    ports:
      - "8086:8086"

